server:
  port: 8081


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak1:
            client-id: oauth2-client-app
            client-name: oauth2-client-app
            client-secret: xSlqD456gfAeLZO93BLbTwQys0NEc8KL
            authorization-grant-type: authorization_code #authorization_code, authorization_code with pkce, implicit
            scope:
              - profile
              - openid
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            provider: keycloak

          keycloakWithPKCE:
            client-id: oauth2-client-app2
            client-name: oauth2-client-app2
            #client-secret: g6jIAAN2lmfg3hgovuydzH3BO61ssAAU
            authorization-grant-type: authorization_code
            scope:
              - profile
              - openid
            client-authentication-method: none
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            provider: keycloak

          keycloak2:
            client-id: oauth2-client-app3
            client-name: oauth2-client-app3
            authorization-grant-type: implicit
            scope:
              - profile
              - openid
            client-authentication-method: none
            redirect-uri: http://localhost:8081/home
            provider: keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

